Update golang, macOS and xcode versions. (#822)
1) Golang is now at 1.21, so add 1.21 and drop 1.19.

2) xcode 11.7 on macOS 11 CI builds have been broken recently, failing
   with error

   ```
   Warning: You are using macOS 11.
   We (and Apple) do not provide support for this old version.
   ...
   Error: Your Xcode (11.7 =>
   /Applications/Xcode_11.7.app/Contents/Developer) is too outdated.
   Please update to Xcode 13.2.1 (or delete it).
   Xcode can be updated from the App Store.
   ```

   Reading https://en.wikipedia.org/wiki/MacOS_Big_Sur, it says that
   macOS 11 is unsupported as of September 26, 2023, so let's drop
   xcode 11.7 and macOS 11.