internal/graph: Support comments with double quotes (#688)
The first comment in a pprof file is used as the subgraph ID for the
legend, but was not escaped. If the comment contained double quotes,
it could cause graphviz to fail to parse the output, or to render
incorrect graphs. To reproduce, run the following commands:

$ pprof -add_comment "unterminated \"double quote" -proto -output=bug.pprof in.pprof
Generating report in labels-no-specials-unterminated-double-quote.pprof
$ pprof -comments bug.pprof
unterminated "double quote
$ pprof -web bug.pprof
Error: <stdin>: syntax error in line 3 near '\'
pprof: failed to execute dot. Is Graphviz installed? Error: exit status 1

Add a test for this case. Without the change to dotgraph.go, the test
produced the following dot output:

digraph "testtitle" {
node [style=filled fillcolor="#f8f8f8"]
subgraph cluster_L { "comment line 1
comment line 2 "unterminated double quote" [shape=box fontsize=16 label="comment line 1\lcomment line 2 \"unterminated double quote\lsecond comment \"double quote\"\l" tooltip="testtitle"] }
N1 [label="src\n10 (10.00%)\nof 25 (25.00%)" id="node1" fontsize=22 shape=box tooltip="src (25)" color="#b23c00" fillcolor="#edddd5"]
N2 [label="dest\n15 (15.00%)\nof 25 (25.00%)" id="node2" fontsize=24 shape=box tooltip="dest (25)" color="#b23c00" fillcolor="#edddd5"]
N1 -> N2 [label=" 10" weight=11 color="#b28559" tooltip="src -> dest (10)" labeltooltip="src -> dest (10)"]
}

This failed to parse with dot:

$ dot ./internal/graph/testdata/compose9.dot
Error: ./internal/graph/testdata/compose9.dot: syntax error in line 4 near '\'

After adding the escaping, the test case now parses with dot, and the
new test case works as expected.